In [105]:
import json

In [106]:
with open('agreementresults4.json', 'r') as f:

    a = json.load(f)

In [107]:
a.keys()

dict_keys(['Jiaao Chen', 'Kayleigh Butera', 'Kehinde Ajibade', 'Mohan', 'Mohan Dodda', 'Pranit Dodda', 'Sebine Lee', 'Sebinne Lee', 'Yun Zhang', 'ZBT', 'ZBT ', 'Zaid Bin Tariq', 'ajibadekehinde1@gmail.com Hi Mohan could you send me an email. I had some technical issues with my Upwork. ', 'check', 'diyi'])

In [108]:
a['Kayleigh Butera']['testannotations'][-1]['fname']

'train_2079'

In [109]:
results_dict = {}

In [110]:
for u in a['Kayleigh Butera']['testannotations']:
    #print(u.keys()) 
    if u['fname'] not in results_dict:
        results_dict[u['fname']] = {}
        
    results_dict[u['fname']]['scores'] = [u['scores']]
    results_dict[u['fname']]['salientInfoAll'] = [u['salientInfoAll']]

In [81]:
# for u in a['Sebinne Lee']['testannotations']:
#     #print(u.keys()) 
#     if u['fname'] not in results_dict:
#         results_dict[u['fname']] = {}
        
#     results_dict[u['fname']]['scores'] = [u['scores']]
#     results_dict[u['fname']]['salientInfoAll'] = [u['salientInfoAll']]

In [125]:
results_dict['train_2079']

{'scores': [{'Salesforce/bart-large-xsum-samsum vs linydub/bart-large-samsum': {'Coverage': -1,
    'Accuracy': -1,
    'Overall Quality': -2,
    'Coherence': 0,
    'Concise': 0},
   'philschmid/distilbart-cnn-12-6-samsum vs knkarthick/meeting-summary-samsum': {'Overall Quality': -1,
    'Coverage': -1,
    'Coherence': 0,
    'Accuracy': 0,
    'Concise': 0},
   'linydub/bart-large-samsum vs knkarthick/meeting-summary-samsum': {'Overall Quality': 0,
    'Accuracy': 0,
    'Concise': 0,
    'Coverage': 0,
    'Coherence': 0}},
  {'Salesforce/bart-large-xsum-samsum vs linydub/bart-large-samsum': {'Coherence': 0,
    'Concise': 0,
    'Accuracy': -1,
    'Coverage': -1,
    'Overall Quality': -2},
   'philschmid/distilbart-cnn-12-6-samsum vs knkarthick/meeting-summary-samsum': {'Overall Quality': -1,
    'Concise': 0,
    'Accuracy': 0,
    'Coverage': -1,
    'Coherence': 0},
   'linydub/bart-large-samsum vs knkarthick/meeting-summary-samsum': {'Coherence': 0,
    'Concise': 0,
    'C

In [118]:
# for u in a['Pranit Dodda']['testannotations']:
#     #print(u.keys()) 
#     if u['fname'] not in results_dict:
#         results_dict[u['fname']] = {}
#         results_dict[u['fname']]['scores'] = [u['scores']]
#         results_dict[u['fname']]['salientInfoAll'] = [u['salientInfoAll']]
#     else:

#         results_dict[u['fname']]['scores'].append(u['scores'])
#         results_dict[u['fname']]['salientInfoAll'].append(u['salientInfoAll'])

In [119]:
# for u in a['Yun Zhang']['testannotations']:
#     #print(u.keys()) 
#     if u['fname'] not in results_dict:
#         results_dict[u['fname']] = {}
#         results_dict[u['fname']]['salientInfoAll'] = [u['salientInfoAll']]
#     else:

#         results_dict[u['fname']]['scores'].append(u['scores'])
#         results_dict[u['fname']]['salientInfoAll'].append(u['salientInfoAll'])
        
# #     results_dict[u['fname']]['scores'].append(u['scores'])
# #     results_dict[u['fname']]['salientInfoAll'].append(u['salientInfoAll'])

In [114]:
# for u in a['Kehinde Ajibade']['testannotations']:
#     #print(u.keys()) 
#     if u['fname'] not in results_dict:
#         results_dict[u['fname']] = {}
#         results_dict[u['fname']]['salientInfoAll'] = [u['salientInfoAll']]
#     else:

#         results_dict[u['fname']]['scores'].append(u['scores'])
#         results_dict[u['fname']]['salientInfoAll'].append(u['salientInfoAll'])
        
# #     results_dict[u['fname']]['scores'].append(u['scores'])
# #     results_dict[u['fname']]['salientInfoAll'].append(u['salientInfoAll'])

In [115]:
# for u in a['Kayleigh Butera']['testannotations']:
#     #print(u.keys()) 
#     if u['fname'] not in results_dict:
#         results_dict[u['fname']] = {}
#         results_dict[u['fname']]['salientInfoAll'] = [u['salientInfoAll']]
#     else:

#         results_dict[u['fname']]['scores'].append(u['scores'])
#         results_dict[u['fname']]['salientInfoAll'].append(u['salientInfoAll'])
        
# #     results_dict[u['fname']]['scores'].append(u['scores'])
# #     results_dict[u['fname']]['salientInfoAll'].append(u['salientInfoAll'])

In [116]:
for u in a['ZBT']['testannotations']:
    #print(u.keys()) 
    if u['fname'] not in results_dict:
        results_dict[u['fname']] = {}
        results_dict[u['fname']]['salientInfoAll'] = [u['salientInfoAll']]
    else:

        results_dict[u['fname']]['scores'].append(u['scores'])
        results_dict[u['fname']]['salientInfoAll'].append(u['salientInfoAll'])
        
#     results_dict[u['fname']]['scores'].append(u['scores'])
#     results_dict[u['fname']]['salientInfoAll'].append(u['salientInfoAll'])

In [120]:
def checkInput(rate, n):
    """ 
    Check correctness of the input matrix
    @param rate - ratings matrix
    @return n - number of raters
    @throws AssertionError 
    """
    N = len(rate)
    k = len(rate[0])
    assert all(len(rate[i]) == k for i in range(k)), "Row length != #categories)"
    #assert all(isinstance(rate[i][j], int) for i in range(N) for j in range(k)), "Element not integer" 
    assert all(sum(row) == n for row in rate), "Sum of ratings != #raters)"

def fleissKappa(rate,n):
    """ 
    Computes the Kappa value
    @param rate - ratings matrix containing number of ratings for each subject per category 
    [size - N X k where N = #subjects and k = #categories]
    @param n - number of raters   
    @return fleiss' kappa
    """

    N = len(rate)
    k = len(rate[0])
    print("#raters = ", n, ", #subjects = ", N, ", #categories = ", k)
    checkInput(rate, n)

    #mean of the extent to which raters agree for the ith subject 
    PA = sum([(sum([i**2 for i in row])- n) / (n * (n - 1)) for row in rate])/N
    print("PA = ", PA)
    
    # mean of squares of proportion of all assignments which were to jth category
    PE = sum([j**2 for j in [sum([rows[i] for rows in rate])/(N*n) for i in range(k)]])
    print("PE =", PE)
    
    kappa = -float("inf")
    try:
        kappa = (PA - PE) / (1 - PE)
        kappa = float("{:.3f}".format(kappa))
    except ZeroDivisionError:
        print("Expected agreement = 1")

    print("Fleiss' Kappa =", kappa)
    
    return kappa

In [121]:
rate = \
    [
        [0,0,0,0,14],
        [0,2,6,4,2],
        [0,0,3,5,6],
        [0,3,9,2,0],
        [2,2,8,1,1],
        [7,7,0,0,0],
        [3,2,6,3,0],
        [2,5,3,2,2],
        [6,5,2,1,0],
        [0,2,2,3,7]
    ]
kappa = fleissKappa(rate,14)

#raters =  14 , #subjects =  10 , #categories =  5
PA =  0.378021978021978
PE = 0.21275510204081632
Fleiss' Kappa = 0.21


In [95]:
results_dict['ZBT']

KeyError: 'ZBT'

In [89]:
# results_dict['train_24']['scores']

In [90]:
# results_dict['train_24']['scores'][0]['Salesforce/bart-large-xsum-samsum vs linydub/bart-large-samsum']

In [126]:
# results_dict['train_24']['scores'][1].keys()
checkl = [2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060]
checkl = [52, 53, 54, 55, 56, 57, 58, 59, 60]
checkl =  [54, 55, 56, 57, 58, 59, 60]
checkl =  [52, 53, 54, 55, 56, 57, 58]
checkl = [2052, 2053, 2054, 2055, 2056, 2057, 2058]#, 2059, 2060]
checkl = [55, 56, 57, 58, 59, 60]
checkl = [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008]
checkl = [2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060]
checkl = [2052, 2053, 2054, 2055, 2056, 2057, 2058, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009]
# checkl = [2000, 2001, 2002, 2003, 2004]
check1 = set([i for i in range(2000, 2049)])-set([2040, 2041, 2037, 2036])
check1 = set([i for i in range(2065, 2075)])-set([2067, 2072, 2071, 2066])
check1 = [2075, 2076, 2077, 2078, 2079]

# check1 = [2000, 2001, 2002, 2003, 2004]
# check1 = [52, 53, 54, 55, 56, 57, 58, 59, 60] +[2000, 2001, 2002, 2003, 2004]

In [127]:
results_dict['train_79'] 

KeyError: 'train_79'

In [128]:
scores = {}
for (u,v) in results_dict.items():
    num = int(u.split('_')[1])
    if num in check1:
#         print(int(u.split('_')[1]), check1, int(u.split('_')[1]) in checkl, u)
        instance_name = u+'_'
        for k in v['scores']:
            for (p, q) in k.items():
                temp = instance_name+p
                if temp not in scores:
                    scores[temp] = []
#                 if len(scores[temp])<2:
                scores[temp].append(q)
        if len(scores[temp])!=3:
            print(u, len(scores[temp]))
        else:
            print('passed', u)
    else:
        print('failed', u)
    


failed train_52
failed train_53
failed train_54
failed train_55
failed train_56
failed train_57
failed train_58
failed train_59
failed train_60
failed train_61
failed train_2000
failed train_2001
failed train_2002
failed train_2003
failed train_2004
failed train_2005
failed train_2006
failed train_2007
failed train_2008
failed train_2009
failed train_2010
failed train_2011
failed train_2012
failed train_2013
failed train_2014
failed train_2015
failed train_2016
failed train_2017
failed train_2018
failed train_2019
failed train_2020
failed train_2021
failed train_2022
failed train_2023
failed train_2024
failed train_2025
failed train_2026
failed train_2027
failed train_2028
failed train_2029
failed train_2030
failed train_2031
failed train_2032
failed train_2033
failed train_2034
failed train_2035
failed train_2036
failed train_2037
failed train_2038
failed train_2039
failed train_2040
failed train_2041
failed train_2042
failed train_2043
failed train_2044
failed train_2045
failed train

In [129]:
scores

{'train_2075_linydub/bart-large-samsum vs knkarthick/meeting-summary-samsum': [{'Coherence': 0,
   'Accuracy': -2,
   'Coverage': -2,
   'Concise': 1,
   'Overall Quality': -2},
  {'Coverage': -2,
   'Overall Quality': -2,
   'Accuracy': 0,
   'Coherence': 0,
   'Concise': 1}],
 'train_2075_philschmid/distilbart-cnn-12-6-samsum vs knkarthick/meeting-summary-samsum': [{'Coherence': 0,
   'Coverage': -2,
   'Overall Quality': -2,
   'Concise': 1,
   'Accuracy': -2},
  {'Coverage': -2,
   'Coherence': 0,
   'Concise': 1,
   'Overall Quality': -2,
   'Accuracy': -1}],
 'train_2075_Salesforce/bart-large-xsum-samsum vs linydub/bart-large-samsum': [{'Concise': -1,
   'Coherence': 0,
   'Overall Quality': 1,
   'Coverage': 1,
   'Accuracy': 0},
  {'Overall Quality': 0,
   'Accuracy': -1,
   'Coherence': 0,
   'Concise': 0,
   'Coverage': 1}],
 'train_2076_Salesforce/bart-large-xsum-samsum vs linydub/bart-large-samsum': [{'Coverage': -2,
   'Coherence': 0,
   'Overall Quality': 0,
   'Concise':

In [130]:
numannotators = 2

In [131]:
import numpy as np
import random

def cal_kappa(name):
    coverage_scores = []

    for (u,v) in scores.items():
        temp = []
        for k in v:
            temp.append(k[name])
        coverage_scores.append(temp)
#     print(coverage_scores)
    raters = np.zeros([len(scores), 5]).astype(int)
    count = 0
    for i in range(0, len(coverage_scores)):
        for k in coverage_scores[i]:
            raters[i][k+2]+=1
#         if i<13:
#             raters[i][0] = 1
#             raters[i][1] = 1
#         else:
# #             num = 0
#             num = random.randint(0, 4)
#             l = random.sample(range(5), 1)
#             num = l[0]
#             raters[i][num] = 2
        
    print(raters)
    kappa = fleissKappa(raters,numannotators)
    
    

In [132]:
coverage_scoress = []
for (u,v) in scores.items():
    temp = []
    for k in v:
        temp.append(k['Coverage'])
    coverage_scoress.append(temp)
coverage_scoress

[[-2, -2],
 [-2, -2],
 [1, 1],
 [-2, -1],
 [-1, -1],
 [-1, 0],
 [0, 1],
 [0, 1],
 [0, -2],
 [2, 2],
 [-2, -2],
 [-2, -2],
 [-1, -1],
 [-1, -1],
 [0, 0]]

In [133]:
arr = np.array(coverage_scoress)


In [134]:
# coverage_scoress = []
# for (u,v) in scores.items():
#     temp = []
#     for k in v:
#         temp.append(k['Coverage'])
#     coverage_scoress.append(temp)
# coverage_scoress

In [135]:
cal_kappa('Coverage')

[[2 0 0 0 0]
 [2 0 0 0 0]
 [0 0 0 2 0]
 [1 1 0 0 0]
 [0 2 0 0 0]
 [0 1 1 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [1 0 1 0 0]
 [0 0 0 0 2]
 [2 0 0 0 0]
 [2 0 0 0 0]
 [0 2 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]]
#raters =  2 , #subjects =  15 , #categories =  5
PA =  0.6666666666666666
PE = 0.24444444444444446
Fleiss' Kappa = 0.559


In [136]:
cal_kappa('Coherence')

[[0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]]
#raters =  2 , #subjects =  15 , #categories =  5
PA =  1.0
PE = 1.0
Fleiss' Kappa = nan


/var/folders/5c/cjd772lx6jq731tvvscmmk9r0000gn/T/ipykernel_56636/1429482093.py:38: RuntimeWarning: invalid value encountered in double_scalars
  kappa = (PA - PE) / (1 - PE)


In [137]:
cal_kappa('Concise')

[[0 0 0 2 0]
 [0 0 0 2 0]
 [0 1 1 0 0]
 [0 0 1 1 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [1 1 0 0 0]
 [0 0 0 0 2]
 [0 0 0 0 2]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]]
#raters =  2 , #subjects =  15 , #categories =  5
PA =  0.8
PE = 0.4111111111111111
Fleiss' Kappa = 0.66


In [138]:
cal_kappa('Accuracy')

[[1 0 1 0 0]
 [1 1 0 0 0]
 [0 1 1 0 0]
 [0 0 1 1 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 2 0]
 [2 0 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 1]
 [0 0 0 2 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]]
#raters =  2 , #subjects =  15 , #categories =  5
PA =  0.6666666666666666
PE = 0.2644444444444444
Fleiss' Kappa = 0.547


In [139]:
cal_kappa('Overall Quality')

[[2 0 0 0 0]
 [2 0 0 0 0]
 [0 0 1 1 0]
 [0 1 1 0 0]
 [2 0 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 1]
 [0 0 0 1 1]
 [2 0 0 0 0]
 [0 0 0 1 1]
 [1 0 1 0 0]
 [1 1 0 0 0]
 [2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]]
#raters =  2 , #subjects =  15 , #categories =  5
PA =  0.5333333333333333
PE = 0.26000000000000006
Fleiss' Kappa = 0.369
